export const VehicleTypes: { name: string; value: string }[] = [
    { name: "Plug-in Hybrid Electric Vehicle (PHEV)", value: "0" },
    { name: "Battery Electric Vehicle (BEV)", value: "2" },
    { name: "Hydrogen Powered Vehicle", value: "1" }
];

export const VehicleModels: { name: string; value: string }[] = [
    { name: 'PS2', value: '0' },
    { name: 'e-tron', value: '2' },
    { name: 'Wheego', value: '3' },
    { name: 'Fortwo Electric Drive', value: '4' },
    { name: 'Soul EV', value: '5' },
    { name: 'Lyriq', value: '7' },
    { name: 'Model X', value: '8' },
    { name: 'X5', value: '9' },
    { name: 'Solterra', value: '10' },
    { name: 'S60', value: '16' },
    { name: 'Ranger', value: '17' },
    { name: 'ELR', value: '20' },
    { name: 'Ioniq 6', value: '21' },
    { name: 'EDV', value: '31' },
    { name: 'Outlander', value: '39' },
    { name: 'B-Class', value: '40' },
    { name: 'e-Golf', value: '41' },
    { name: 'Roadster', value: '44' },
    { name: 'Kona', value: '47' },
    { name: '918', value: '57' },
    { name: 'R1T', value: '58' },
    { name: 'Range Rover', value: '59' },
    { name: 'TONALE', value: '61' },
    { name: 'Mustang Mach-E', value: '62' },
    { name: 'XC40', value: '63' },
    { name: 'RZ 450e', value: '65' },
    { name: 'Voyager', value: '66' },
    { name: 'NX', value: '67' },
    { name: 'CX-90', value: '68' },
    { name: 'GV70', value: '69' },
    { name: 'bZ4X', value: '70' },
    { name: '530e', value: '72' },
    { name: 'i-MiEV', value: '73' },
    { name: 'C-Max', value: '75' },
    { name: 'Grand Cherokee', value: '79' },
    { name: 'Panamera', value: '80' },
    { name: 'Bubble Buddy', value: '81' },
    { name: 'ARIYA', value: '82' },
    { name: 'i8', value: '83' },
    { name: 'Flying Spur', value: '84' },
    { name: '745e', value: '85' },
    { name: 'RS e-tron GT', value: '86' },
    { name: 'i4', value: '87' },
    { name: 'EQE-Class Sedan', value: '88' },
    { name: 'EQE-Class SUV', value: '89' },
    { name: 'Focus', value: '93' },
    { name: 'A3', value: '94' },
    { name: 'Santa Fe', value: '95' },
    { name: 'Prius Prime', value: '97' },
    { name: 'Transit', value: '98' },
    { name: 'Bolt EV', value: '99' },
    { name: 'Pacifica', value: '101' },
    { name: 'GLE-Class', value: '102' },
    { name: 'Q5', value: '103' },
    { name: 'Q5 e', value: '104' },
    { name: 'C40', value: '105' },
    { name: 'Model S', value: '106' },
    { name: 'GV60', value: '109' },
    { name: 'i3', value: '111' },
    { name: 'Model 3', value: '112' },
    { name: 'Fortwo', value: '113' },
    { name: 'Spark', value: '117' },
    { name: 'Model Y', value: '118' },
    { name: 'A8 e', value: '119' },
    { name: 'Fusion', value: '120' },
    { name: 'ID.4', value: '121' },
    { name: 'Prius Plug-in', value: '122' },
    { name: 'Niro', value: '124' },
    { name: 'Cayenne', value: '125' },
    { name: 'Taycan', value: '126' },
    { name: 'e-tron Sportback', value: '128' },
    { name: 'F-150', value: '129' },
    { name: 'I-PACE', value: '130' },
    { name: '740e', value: '131' }
];

export const VehiclePrimaryUses: { name: string; value: string }[] = [
    { name: 'Neighborhood Electric Vehicle', value: '0' },
    { name: 'For Hire', value: '1' },
    { name: 'Commercial', value: '2' },
    { name: 'Taxi Cab', value: '3' },
    { name: 'Exempt (State/County/Local/Tribal)', value: '4' },
    { name: 'Private School', value: '5' },
    { name: 'Cab', value: '6' },
    { name: 'Passenger', value: '7' },
    { name: 'Farm Use', value: '8' },
    { name: 'Truck', value: '9' },
    { name: 'Medium-Speed Electric Vehicle', value: '10' },
    { name: 'Medium-Speed Electric Truck', value: '11' },
    { name: 'Farm Exempt', value: '12' }
];
