export const VehicleTypes: { name: string; value: string }[] = [
    { name: "Plug-in Hybrid Electric Vehicle (PHEV)", value: "0" },
    { name: "Battery Electric Vehicle (BEV)", value: "2" },
    { name: "Hydrogen Powered Vehicle", value: "1" }
];

export const VehicleModels: { name: string; value: string }[] = [
    { name: 'TONALE', value: '0' },
    { name: 'e-tron', value: '1' },
    { name: 'Q4', value: '2' },
    { name: 'Q5', value: '3' },
    { name: 'Q5 e', value: '4' },
    { name: 'RS e-tron GT', value: '5' },
    { name: 'Q8', value: '6' },
    { name: 'A3', value: '7' },
    { name: 'A7', value: '8' },
    { name: 'A8 e', value: '9' },
    { name: 'e-tron Sportback', value: '10' },
    { name: 'e-tron GT', value: '11' },
    { name: 'Transit Connect Electric', value: '12' },
    { name: 'Flying Spur', value: '13' },
    { name: 'Bentayga', value: '14' },
    { name: 'i3', value: '15' },
    { name: '530e', value: '16' },
    { name: '740e', value: '17' },
    { name: '745e', value: '18' },
    { name: '745Le', value: '19' },
    { name: 'X5', value: '20' },
    { name: 'X3', value: '21' },
    { name: '330e', value: '22' },
    { name: 'iX', value: '23' },
    { name: 'i8', value: '24' },
    { name: 'i4', value: '25' },
    { name: 'Bubble Buddy', value: '26' },
    { name: 'ELR', value: '27' },
    { name: 'Lyriq', value: '28' },
    { name: 'CT6', value: '29' },
    { name: 'S-10 Pickup', value: '30' },
    { name: 'Bolt EV', value: '31' },
    { name: 'Bolt EUV', value: '32' },
    { name: 'Spark', value: '33' },
    { name: 'Volt', value: '34' },
    { name: 'Pacifica', value: '35' },
    { name: 'Caravan', value: '36' },
    { name: '500', value: '37' },
    { name: 'Karma', value: '38' },
    { name: 'Ranger', value: '39' },
    { name: 'C-Max', value: '40' },
    { name: 'Escape', value: '41' },
    { name: 'F-150', value: '42' },
    { name: 'Focus', value: '43' },
    { name: 'Fusion', value: '44' },
    { name: 'Mustang Mach-E', value: '45' },
    { name: 'Transit', value: '46' },
    { name: 'G80', value: '47' },
    { name: 'GV70', value: '48' },
    { name: 'GV60', value: '49' },
    { name: 'Accord', value: '50' },
    { name: 'Fit', value: '51' },
    { name: 'Clarity', value: '52' },
    { name: 'Tucson', value: '53' },
    { name: 'Ioniq', value: '54' },
    { name: 'IONIQ 5', value: '55' },
    { name: 'Ioniq 6', value: '56' },
    { name: 'Kona', value: '57' },
    { name: 'Kona Electric', value: '58' },
    { name: 'Santa Fe', value: '59' },
    { name: 'Sonata', value: '60' },
    { name: 'I-PACE', value: '61' },
    { name: 'Grand Cherokee', value: '62' },
    { name: 'Wrangler', value: '63' },
    { name: 'EV6', value: '64' },
    { name: 'Niro', value: '65' },
    { name: 'Optima', value: '66' },
    { name: 'Sportage', value: '67' },
    { name: 'Soul EV', value: '68' },
    { name: 'Soul', value: '69' },
    { name: 'Sorento', value: '70' },
    { name: 'Range Rover Sport', value: '71' },
    { name: 'Range Rover', value: '72' },
    { name: 'RZ 450e', value: '73' },
    { name: 'NX', value: '74' },
    { name: 'Corsair', value: '75' },
    { name: 'Aviator', value: '76' },
    { name: 'Air', value: '77' },
    { name: 'CX-90', value: '78' },
    { name: 'EQS-Class SUV', value: '79' },
    { name: 'C-Class', value: '80' },
    { name: 'GLC-Class', value: '81' },
    { name: 'B-Class', value: '82' },
    { name: 'EQE-Class Sedan', value: '83' },
    { name: 'S-Class', value: '84' },
    { name: 'EQB-Class', value: '85' },
    { name: 'EQE-Class SUV', value: '86' },
    { name: 'EQS-Class Sedan', value: '87' },
    { name: 'GLE-Class', value: '88' },
    { name: 'Hardtop', value: '89' },
    { name: 'Countryman', value: '90' },
    { name: 'Outlander', value: '91' },
    { name: 'i-MiEV', value: '92' },
    { name: 'Leaf', value: '93' },
    { name: 'ARIYA', value: '94' },
    { name: 'Voyager', value: '95' },
    { name: 'PS2', value: '96' },
    { name: 'Cayenne', value: '97' },
    { name: 'Taycan', value: '98' },
    { name: 'Panamera', value: '99' },
    { name: '918', value: '100' },
    { name: 'R1T', value: '101' },
    { name: 'EDV', value: '102' },
    { name: 'R1S', value: '103' },
    { name: 'EQ Fortwo', value: '104' },
    { name: 'Fortwo Electric Drive', value: '105' },
    { name: 'Fortwo', value: '106' },
    { name: 'Solterra', value: '107' },
    { name: 'Crosstrek', value: '108' },
    { name: 'Model Y', value: '109' },
    { name: 'Roadster', value: '110' },
    { name: 'Model X', value: '111' },
    { name: 'Model S', value: '112' },
    { name: 'Model 3', value: '113' },
    { name: 'City', value: '114' },
    { name: 'Prius Plug-in', value: '115' },
    { name: 'PRIUS', value: '116' },
    { name: 'Prius Prime', value: '117' },
    { name: 'RAV4 Prime', value: '118' },
    { name: 'bZ4X', value: '119' },
    { name: 'Mirai', value: '120' },
    { name: 'RAV4', value: '121' },
    { name: 'ID.4', value: '122' },
    { name: 'e-Golf', value: '123' },
    { name: 'XC60', value: '124' },
    { name: 'S60', value: '125' },
    { name: 'XC40', value: '126' },
    { name: 'XC90', value: '127' },
    { name: 'S90', value: '128' },
    { name: 'V60', value: '129' },
    { name: 'C40', value: '130' },
    { name: 'Wheego', value: '131' },
];

export const VehiclePrimaryUses: { name: string; value: string }[] = [
    { name: 'Cab', value: '0' },
    { name: 'Commercial', value: '1' },
    { name: 'Exempt (State/County/Local/Tribal)', value: '2' },
    { name: 'Farm Exempt', value: '3' },
    { name: 'Farm Use', value: '4' },
    { name: 'For Hire', value: '5' },
    { name: 'Medium-Speed Electric Truck', value: '6' },
    { name: 'Medium-Speed Electric Vehicle', value: '7' },
    { name: 'Neighborhood Electric Vehicle', value: '8' },
    { name: 'Passenger', value: '9' },
    { name: 'Private School', value: '10' },
    { name: 'Taxi Cab', value: '11' },
    { name: 'Truck', value: '12' },
];

export const VehicleMake: { name: string; value: string }[] = [
    { name: 'ALFA ROMEO', value: '1' },
    { name: 'AUDI', value: '2' },
    { name: 'AZURE DYNAMICS', value: '3' },
    { name: 'BENTLEY', value: '4' },
    { name: 'BMW', value: '5' },
    { name: 'BUBBLE BUDDY', value: '6' },
    { name: 'CADILLAC', value: '7' },
    { name: 'CHEVROLET', value: '8' },
    { name: 'CHRYSLER', value: '9' },
    { name: 'DODGE', value: '10' },
    { name: 'FIAT', value: '11' },
    { name: 'FISKER', value: '12' },
    { name: 'FORD', value: '13' },
    { name: 'GENESIS', value: '14' },
    { name: 'HONDA', value: '15' },
    { name: 'HYUNDAI', value: '16' },
    { name: 'JAGUAR', value: '17' },
    { name: 'JEEP', value: '18' },
    { name: 'KIA', value: '19' },
    { name: 'LAND ROVER', value: '20' },
    { name: 'LEXUS', value: '21' },
    { name: 'LINCOLN', value: '22' },
    { name: 'LUCID', value: '23' },
    { name: 'MAZDA', value: '24' },
    { name: 'MERCEDES-BENZ', value: '25' },
    { name: 'MINI', value: '26' },
    { name: 'MITSUBISHI', value: '27' },
    { name: 'NISSAN', value: '28' },
    { name: 'PLYMOUTH', value: '29' },
    { name: 'POLESTAR', value: '30' },
    { name: 'PORSCHE', value: '31' },
    { name: 'RIVIAN', value: '32' },
    { name: 'SMART', value: '33' },
    { name: 'SUBARU', value: '34' },
    { name: 'TESLA', value: '35' },
    { name: 'TH!NK', value: '36' },
    { name: 'TOYOTA', value: '37' },
    { name: 'VOLKSWAGEN', value: '38' },
    { name: 'VOLVO', value: '39' },
    { name: 'WHEEGO ELECTRIC CARS', value: '40' }
];

